hotels_GSM = {
  "هتل لاچین": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "لاچین",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل نخل هنگام": {
    "dayan": "",
    "deltaban": "",
    "alwin": "نخل هنگام",
    "rahbal": "",
    "HRC": "",
    "booking": "نخل هنگام",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل الاله": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "الاله",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل ریحان": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "ریحان",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل آوینا": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "آوینا",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 4
  },
  "هتل شهریار": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "شهریار",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل آسمان": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "آسمان",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل آرش": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "آرش",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل خلیج فارس": {
    "dayan": "خلیج فارس",
    "deltaban": "",
    "alwin": "",
    "rahbal": "خليج فارس",
    "HRC": "",
    "booking": "خلیج فارس",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل آرتا": {
    "dayan": "",
    "deltaban": "",
    "alwin": "ارتا",
    "rahbal": "",
    "HRC": "",
    "booking": "آرتا",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 4
  },
  "هتل قصر الوند": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "booking": "قصر الوند",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل آرمان": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "آرمان",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل الوند ۱": {
    "dayan": "",
    "deltaban": "",
    "alwin": "الوند",
    "rahbal": "الوند",
    "HRC": "",
    "booking": "الوند",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل پاک": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "پاک",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },

  "هتل رخسار": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "رخسار",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },

  "هتل سارينا": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "سارينا",
    "HRC": "سارينا",
    "booking": "سارينا",
    "mehrab": "سارينا",
    "tak": "سارينا",
    "shayan": "سارينا",
    "felamingo": "سارينا",
    "yeganeh": "سارينا",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },

  "هتل سما": {
    "dayan": "",
    "deltaban": "سما",
    "alwin": "سما",
    "rahbal": "",
    "HRC": "",
    "booking": "سما",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل ساحل طلایی": {
    "dayan": "",
    "deltaban": "ساحل طلایی",
    "alwin": "ساحل طلایی",
    "rahbal": "",
    "HRC": "",
    "booking": "ساحل طلایی",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "بوتیک ایرمان": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "booking": "ایرمان",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل کاوان": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "کاوان",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل دیانا پلاس": {
    "dayan": "",
    "deltaban": "",
    "alwin": "دیانا پالاس",
    "rahbal": "",
    "HRC": "",
    "booking": "دیانا پالاس",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل سان سیتی": {
    "dayan": "",
    "deltaban": "",
    "alwin": "سان سیتی",
    "rahbal": "",
    "HRC": "",
    "booking": "سان سیتی",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل آرام": {
    "dayan": "",
    "deltaban": "ارام",
    "alwin": "ارام",
    "rahbal": "",
    "HRC": "",
    "booking": "ارام",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل مروارید": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "مروارید",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 1
  },
  "هتل شاد ناز ۱": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل قباد": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل آسماری": {
    "dayan": "",
    "deltaban": "اسماری",
    "alwin": "اسماری",
    "rahbal": "",
    "HRC": "",
    "booking": "اسماری",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 2
  },
  "هتل آلاله مرکزی": {
    "dayan": "",
    "deltaban": "الاله مرکزی",
    "alwin": "الاله مرکزی",
    "rahbal": "",
    "HRC": "",
    "booking": "الاله مرکزی",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل مارینا": {
    "dayan": "",
    "deltaban": "مارینا",
    "alwin": "مارینا",
    "rahbal": "",
    "HRC": "",
    "booking": "مارینا",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل مریم": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "مریم",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل رویال": {
    "dayan": "",
    "deltaban": "رویال",
    "alwin": "رویال",
    "rahbal": "",
    "HRC": "",
    "booking": "رویال",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل سینگو": {
    "dayan": "",
    "deltaban": "سینگو",
    "alwin": "سینگو",
    "rahbal": "",
    "HRC": "",
    "booking": "سینگو",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل پرشین گلف": {
    "dayan": "پرشین گلف",
    "deltaban": "پرشین گلف",
    "alwin": "پرشین گلف",
    "rahbal": "پرشین گلف",
    "HRC": "",
    "booking": "پرشین گلف",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل بهشت": {
    "dayan": "بهشت",
    "deltaban": "بهشت",
    "alwin": "بهشت",
    "rahbal": "بهشت",
    "HRC": "",
    "booking": "بهشت",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل شمس": {
    "dayan": "",
    "deltaban": "",
    "alwin": "شمس",
    "rahbal": "شمس",
    "HRC": "",
    "booking": "شمس",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "بوتیک فولتون": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "فولتون",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل دیاموند": {
    "dayan": "",
    "deltaban": "",
    "alwin": "دیاموند",
    "rahbal": "",
    "HRC": "",
    "booking": "دیاموند",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل هانی": {
    "dayan": "هانی",
    "deltaban": "هانی",
    "alwin": "هانی",
    "rahbal": "",
    "HRC": "",
    "booking": "هانی",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 4
  },
  "هتل آرکا": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "ارکا",
    "HRC": "",
    "booking": "آرکا",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل ارم": {
    "dayan": "",
    "deltaban": "",
    "alwin": "ارم",
    "rahbal": "",
    "HRC": "",
    "booking": "ارم",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 4
  },
  "هتل آسانا": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل آتاسان": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل ویهان": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل کیمیا ۴": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "",
    "booking": "",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  },
  "هتل پلاس 1": {
    "dayan": "",
    "deltaban": "",
    "alwin": "",
    "rahbal": "",
    "HRC": "پ",
    "booking": "",
    "mehrab": "",
    "tak": "",
    "shayan": "",
    "felamingo": "",
    "yeganeh": "",
    "iman": "",
    "hammod": "",
    "safiran": "",
    "dolfin": "",
    "hotel_star": 3
  }
}