hotels = {
    "هتل لاچین": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل نخل هنگام": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل الاله ۲": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل ریحان ۲": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آوینا": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل شهریار": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آسمان": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آرش": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل خلیج فارس": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آرتا": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل قصر الوند (الوند ۲)": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آرمان": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل الوند ۱": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل پاک": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل رخسار": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل سما ۲": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل ساحل طلایی": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "بوتیک ایرمان": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل سما": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل کاوان": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل دیانا پلاس": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل سان سیتی": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آرام": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل مروارید": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل شاد ناز ۱": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل قباد": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آسماری": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آلاله مرکزی": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل مارینا ۲": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل مارینا ۱": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل مریم": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل رویال": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل سینگو": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل پرشین گلف": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل بهشت": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل شمس": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "بوتیک فولتون": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل دیاموند": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل هانی": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آرکا": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل ارم": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آسانا": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل آتاسان": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل ویهان": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
    "هتل کیمیا ۴": {
        "dayan": None,
        "deltaban": None,
        "alwin": None,
        "rahbal": None,
        "hotel_star": 3,
    },
}
